"""Prepare deterministic, provenance-aware Chinese-definition work batches."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MASTER = (
    ROOT
    / "data_sources/clean/release_word_master_3800/release_word_master_3800.csv"
)
DEFAULT_SEMANTICS = (
    ROOT / "data_sources/enrichment/oewn_semantic_base/oewn_semantic_base.json"
)
DEFAULT_POS = (
    ROOT
    / "data_sources/enrichment/non_oewn_pos_supplement/release_3800_pos_evidence.csv"
)
DEFAULT_OUTPUT = ROOT / "data_sources/enrichment/chinese_definition_batches"


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_json(path: Path, value: object) -> None:
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--master", type=Path, default=DEFAULT_MASTER)
    parser.add_argument("--semantics", type=Path, default=DEFAULT_SEMANTICS)
    parser.add_argument("--pos", type=Path, default=DEFAULT_POS)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--batch-size", type=int, default=100)
    args = parser.parse_args()

    if args.batch_size < 1:
        raise ValueError("batch size must be positive")

    master = read_csv(args.master)
    semantic_obj = json.loads(args.semantics.read_text(encoding="utf-8"))
    semantics = semantic_obj["records"]
    pos_rows = read_csv(args.pos)

    if len(master) != 3800:
        raise ValueError(f"expected 3800 master records, got {len(master)}")

    def keyed(rows: list[dict[str, object]], label: str) -> dict[str, dict[str, object]]:
        output: dict[str, dict[str, object]] = {}
        for row in rows:
            record_id = str(row["record_id"])
            if record_id in output:
                raise ValueError(f"duplicate {label} record_id: {record_id}")
            output[record_id] = row
        return output

    semantic_by_id = keyed(semantics, "semantic")
    pos_by_id = keyed(pos_rows, "POS")
    master_ids = {row["record_id"] for row in master}
    if set(semantic_by_id) != master_ids or set(pos_by_id) != master_ids:
        raise ValueError("master, semantic, and POS record IDs do not match")

    args.output_dir.mkdir(parents=True, exist_ok=True)
    # Remove only files generated by this script so a changed batch size cannot
    # leave stale batch files in the evidence directory.
    for stale in args.output_dir.glob("batch_[0-9][0-9][0-9].json"):
        stale.unlink()

    manifest_batches: list[dict[str, object]] = []
    all_records: list[dict[str, object]] = []
    for master_row in master:
        record_id = master_row["record_id"]
        semantic = semantic_by_id[record_id]
        pos = pos_by_id[record_id]
        senses = [
            {
                "sense_id": sense["sense_id"],
                "synset_id": sense["synset_id"],
                "part_of_speech": sense["part_of_speech"],
                "lexicographer_class": sense["lexicographer_class"],
                "definitions_en": sense["definitions_en"],
            }
            for sense in semantic["senses"]
        ]
        no_oewn_semantics = not senses
        all_records.append(
            {
                "record_id": record_id,
                "word": master_row["word"],
                "variants": [x for x in master_row["variants"].split("|") if x],
                "dataset_layer": master_row["dataset_layer"],
                "curriculum_level": master_row["curriculum_level"],
                "pos_evidence": [
                    x for x in pos["parts_of_speech"].split("|") if x
                ],
                "pos_evidence_source": pos["pos_evidence_source"],
                "oewn_match_status": semantic["match_status"],
                "candidate_senses": senses,
                "semantic_warning": (
                    "no_oewn_semantics_requires_controlled_research"
                    if no_oewn_semantics
                    else "candidate_senses_require_selection_not_bulk_translation"
                ),
                "selected_source_sense_ids": [],
                "definitions_zh": [],
                "display_parts_of_speech": [],
                "draft_method": "AI_drafted_from_open_source_semantics",
                "definition_status": "pending_ai_draft",
                "qa_status": "not_checked",
                "qa_notes": [],
            }
        )

    for offset in range(0, len(all_records), args.batch_size):
        batch_number = offset // args.batch_size + 1
        records = all_records[offset : offset + args.batch_size]
        filename = f"batch_{batch_number:03d}.json"
        batch_path = args.output_dir / filename
        payload = {
            "schema_version": 1,
            "batch_id": f"zh-definition-batch-{batch_number:03d}",
            "record_count": len(records),
            "source_policy": {
                "old_chinese_definitions_allowed": False,
                "ecdict_translation_allowed": False,
                "primary_semantic_source": "Open English WordNet 2025",
                "draft_rule": "Select useful senses first, then write concise original Chinese definitions.",
            },
            "records": records,
        }
        write_json(batch_path, payload)
        manifest_batches.append(
            {
                "batch_id": payload["batch_id"],
                "file": filename,
                "record_count": len(records),
                "first_record_id": records[0]["record_id"],
                "last_record_id": records[-1]["record_id"],
                "no_oewn_semantics_count": sum(
                    not row["candidate_senses"] for row in records
                ),
                "sha256": sha256(batch_path),
            }
        )

    manifest = {
        "schema_version": 1,
        "dataset_id": "engmaster-chinese-definition-work-batches-3800",
        "record_count": len(all_records),
        "batch_size": args.batch_size,
        "batch_count": len(manifest_batches),
        "pending_ai_draft_count": len(all_records),
        "no_oewn_semantics_count": sum(
            not row["candidate_senses"] for row in all_records
        ),
        "inputs": {
            "master": str(args.master.relative_to(ROOT)).replace("\\", "/"),
            "master_sha256": sha256(args.master),
            "semantics": str(args.semantics.relative_to(ROOT)).replace("\\", "/"),
            "semantics_sha256": sha256(args.semantics),
            "pos": str(args.pos.relative_to(ROOT)).replace("\\", "/"),
            "pos_sha256": sha256(args.pos),
        },
        "batches": manifest_batches,
    }
    write_json(args.output_dir / "batch_manifest.json", manifest)

    readme = """# 中文释义重建工作批次

本目录把 3,800 条发布词目按固定顺序拆成每批 100 条，共 38 批。批次只包含开放来源的英文语义证据、词性证据和空白中文目标字段，不含旧词表中文释义。

## 编写规则

1. 先选择适合中学学习的英文义项，再用自己的中文表述写简洁释义；不得逐项机械翻译全部 WordNet 义项。
2. `selected_source_sense_ids` 记录采用的 OEWN sense ID；没有 OEWN 义项时，必须在 `qa_notes` 记录补充判断依据。
3. `definitions_zh` 中每项使用结构 `{\"part_of_speech\": \"...\", \"definition\": \"...\"}`。
4. `display_parts_of_speech` 只保留最终展示需要的词性，不能照搬来源里所有历史或生僻词性。
5. 完成初稿后将 `definition_status` 改为 `ai_draft_complete`；通过自动检查后再改 `qa_status`，不得直接标记人工审核。

## 风险控制

- 不读取、不复制 `assets/vocabulary.json` 的中文释义、音标或例句。
- 不使用 ECDICT 的 translation 字段。ECDICT 在前一阶段仅用于词目存在性核对。
- OEWN 义项是候选证据，不保证覆盖冠词、介词、连词等教学常用语法义。例如 `a` 可能只匹配到字母名词义，因此所有词都必须经过义项选择。
- `no_oewn_semantics_requires_controlled_research` 项目需要单独补充可说明的判断依据。

批次文件由 `tools/prepare_chinese_definition_batches.py` 可重复生成，输入文件哈希和每批哈希见 `batch_manifest.json`。
"""
    (args.output_dir / "README.md").write_text(readme, encoding="utf-8")

    checksum_targets = sorted(args.output_dir.glob("batch_*.json")) + [
        args.output_dir / "README.md"
    ]
    checksum_lines = [
        f"{sha256(path)}  {path.name}" for path in checksum_targets
    ]
    (args.output_dir / "SHA256SUMS.txt").write_text(
        "\n".join(checksum_lines) + "\n", encoding="ascii"
    )

    print(
        f"prepared {len(all_records)} records in {len(manifest_batches)} batches; "
        f"{manifest['no_oewn_semantics_count']} require controlled research"
    )


if __name__ == "__main__":
    main()
