name: Build-EXE
on:
  workflow_dispatch:
  push:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install
      run: |
        pip install pyinstaller

    - name: Run-Build
      run: |
        python -m PyInstaller --onefile --windowed main.py

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: My-Windows-Program
        path: dist/